CREATE DATABASE bitbucket;
GRANT ALL PRIVILEGES ON DATABASE bitbucket TO postgres;
CREATE DATABASE confluence;
GRANT ALL PRIVILEGES ON DATABASE confluence TO postgres;
CREATE DATABASE jira;
GRANT ALL PRIVILEGES ON DATABASE jira TO postgres;
